PATCH http://localhost:3001/api/blogs/668c1e4b2dde35b560bc8197
Content-Type: application/json

{
    "author":"Skibid gyatt"
}

#   title: String,
#   author: String,
#   url: String,
#   likes: Number