POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "username1",
    "name": "Mikko Mikkonen",
    "password": "drowssap"
}

#   title: String,
#   author: String,
#   url: String,
#   likes: Number